services:
    db:
        image: mysql
        container_name: gopharma-db
        ports:
            - '3306:3306'
        environment:
            - MYSQL_DATABASE=gopharma
            - MYSQL_PASSWORD=Caracas.2021*
            - MYSQL_ROOT_PASSWORD=Caracas.2021*
        restart: always
        volumes:
            - gopharma-db-conf.d:/etc/mysql/conf.d
            - gopharma-db-mysql:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 3


    backend:
        container_name: gopharma-backend
        build:
            dockerfile: Dockerfile
            target: ${NODE_ENV}
        env_file:
            - .env
        ports:
            - '${SERVER_PORT}:${SERVER_PORT}'
        expose:
            - ${SERVER_PORT}
        depends_on:
            db:
                condition: service_healthy

        restart: always
        volumes:
            - ./src:/app/src
            - gopharma-uploads:/app/uploads
        command: npm run start:dev  # Ejecuta Next.js en modo desarrollo con hot-reloading

    frontend:
        container_name: gopharma-frontend
        build:
            context: ../frontend
            dockerfile: Dockerfile
            target: ${NODE_ENV}
        env_file:
            - ../frontend/.env
        ports:
            - '${FRONTEND_PORT}:${FRONTEND_PORT}'
        expose:
            - ${FRONTEND_PORT}
        depends_on:
            - backend
        volumes:
            - ../frontend:/app
            - /app/node_modules
            - ../frontend:/app:delegated  # Mejora el rendimiento en Windows/macOS
        command: npm run dev  # Ejecuta Next.js en modo desarrollo con hot-reloading
        restart: always

volumes:
    gopharma-db-conf.d:
    gopharma-db-mysql:
    gopharma-uploads:
