import { DataSource } from 'typeorm';
import { Seeder } from 'typeorm-extension';
import { Treasury_maintenance_Bank } from 'src/modules/treasury/maintenance/banks/entities/bank.entity';

export class BankSeeder1721921642958 implements Seeder {
    track = false;

    public async run(dataSource: DataSource): Promise<any> {
        const repository = dataSource.getRepository(Treasury_maintenance_Bank);

        const banks = [
            {
                branch: 'Sucursal 1',
                name: 'Banco de Venezuela',
                adress: 'Carrera 123',
                bankCode: '0102',
                ssn: '1234567890',
                phone: '0212-1234567',
                email: 'bancodevenezuela@banco.com',
                aba: '1234567890',
                routeNumber: '1234567890',
                swift: '1234567890',
                urbanization: 'Urbanización 1',
                street: 'Calle 1',
                building: '123',
                municipality: 'San Francisco',
                city: 'Caracas',
                codeZip: '1010',
                isActive: true,
            },
            {
                branch: 'Sucursal 2',
                name: 'Banco Provincial',
                adress: 'Avenida 45',
                bankCode: '0108',
                ssn: '0987654321',
                phone: '0212-7654321',
                email: 'bancoprovincial@banco.com',
                aba: '0987654321',
                routeNumber: '0987654321',
                swift: '0987654321',
                urbanization: 'Urbanización 2',
                street: 'Calle 2',
                building: '456',
                municipality: 'Libertador',
                city: 'Caracas',
                codeZip: '1020',
                isActive: true,
            },
            {
                branch: 'Sucursal 3',
                name: 'Banco Mercantil',
                adress: 'Plaza Mayor',
                bankCode: '0105',
                ssn: '1122334455',
                phone: '0212-3344556',
                email: 'bancodevenezuela@banco.com',
                aba: '1122334455',
                routeNumber: '1122334455',
                swift: '1122334455',
                urbanization: 'Urbanización 3',
                street: 'Calle 3',
                building: '789',
                municipality: 'Chacao',
                city: 'Caracas',
                codeZip: '1030',
                isActive: true,
            },
            // Agrega más bancos aquí
            {
                branch: 'Sucursal 4',
                name: 'Banco Exterior',
                adress: 'Avenida Principal',
                bankCode: '0115',
                ssn: '2233445566',
                phone: '0212-4455667',
                email: 'bancoexterior@banco.com',
                aba: '2233445566',
                routeNumber: '2233445566',
                swift: '2233445566',
                urbanization: 'Urbanización 4',
                street: 'Calle 4',
                building: '101',
                municipality: 'Baruta',
                city: 'Caracas',
                codeZip: '1040',
                isActive: true,
            },
            {
                branch: 'Sucursal 5',
                name: 'Banesco',
                adress: 'Calle Principal',
                bankCode: '0134',
                ssn: '3344556677',
                phone: '0212-5566778',
                email: 'banesco@banco.com',
                aba: '3344556677',
                routeNumber: '3344556677',
                swift: '3344556677',
                urbanization: 'Urbanización 5',
                street: 'Calle 5',
                building: '202',
                municipality: 'El Hatillo',
                city: 'Caracas',
                codeZip: '1050',
                isActive: true,
            },
            {
                branch: 'Sucursal 6',
                name: 'Banco del Tesoro',
                adress: 'Avenida Bolívar',
                bankCode: '0163',
                ssn: '4455667788',
                phone: '0212-6677889',
                email: 'bancodeltesoro@banco.com',
                aba: '4455667788',
                routeNumber: '4455667788',
                swift: '4455667788',
                urbanization: 'Urbanización 6',
                street: 'Calle 6',
                building: '303',
                municipality: 'Sucre',
                city: 'Caracas',
                codeZip: '1060',
                isActive: true,
            },
        ];

        await repository.save(banks);
    }
}

